### PR TITLE
add newPostion to props

### PR DESCRIPTION
**Pull request by garris**
Added the ability to update scrubber position via newPostition property.

Also bumped deps and included new /index.js.

We're using this in BackstopJS.  Thanks.

### CODE REVIEW

**Comment by jacobp100** [comment]
Good idea! I think we should follow how React does this for inputs:

* Change `initialPosition` to `defaultPosition` for an uncontrolled component
* Add `position` and `onChange` props for a controlled component

**Comment by garris** [comment]
Hi @jacobp100.  I am not familiar with controlled/uncontrolled conventions— could you add some more details or a code sample or maybe point me to an online resource?

**Comment by jacobp100** [comment]
Published the change on v1.1.0.

> You can also use this component as a controlled component. Just provide the props position, and listen to the onChange event, which will called with a number when the slider is moved.

You can look into the [demo](https://github.com/jacobp100/react-twentytwenty/blob/gh-pages/demo/index.js) for an example.

Let me know if you have any issues!

Thanks anyway for the PR!

**Comment by garris** [comment]
Fantastic— thank you!

**Pull request closed without merging**
